---
- hosts: windows2012r2
  tasks:
   - name: windows_updates
      win_updates:
	    category_names: 
		    Application;Connectors;CriticalUpdates;DefinitionUpdates;DeveloperKits;FeaturePacks;Guidance;SecurityUpdates;ServicePacks;Tools;UpdateRollups;
      reboot_timeout: 1200
      log_path: undefined
      whitelist: undefined
      reboot: yes 
      use_scheduled_task: no 
      blacklist: undefined 
      state: searched
